
SOL 144
$ Vortex lattice solver parameters
$-------2-------3-------4-------5-------6-------7-------8-------9-------10
AEROS                   2.5     28      255     0       0       0       
$
SUPORT  1       1005    123456  
$

$
$ Flight condition parameters
$
TRIM= 1, Cruise/Climb
$-------2-------3-------4-------5-------6-------7-------8-------9-------10
$
$  ID: 1
$
$ CRUISE/CLIMB determine:
$  alpha   
$  acc_x   
$  Elevator
$ Input: acc_z,.
$
TRIM    1       1       0.5     5000    SIDES   0       ROLL    0       
        PITCH   0       YAW     0       URDD2   0       URDD3   9.81    
        URDD4   0       URDD5   0       URDD6   0       flap1r  0       
        flap2r  0       aileronr0       rudder1 0       CLIMB   0       
        BANK    0       HEAD    0       THRUST  0       
$
$-------2-------3-------4-------5-------6-------7-------8-------9-------10

