$
$ SPEEDS (EAS):
$ - Maneuvering          VA:  139.465 [m/s].
$ - Rough air            VB:  -1 [m/s].
$ - Design min cruise    VC:  135.079 [m/s].
$ - Design cruise       VMO:  143.184 [m/s].
$ - Design dive          VD:  178.091 [m/s].
$ - Stall clean conf.    VS:  88.2053 [m/s].
$ - Stall landing conf. VFLAND: -1 [m/s].
$      Percentage MTOW used: 79.1%
$ - Flap design          VF:  -1 [m/s].
$
$ MACH:
$ - Design cruise MMO:  0.8904.
$ - Design dive    MD:  0.885978.
$
$ LOAD FACTORS:
$ - Max nz: 2.5.
$ - Min nz: -1.
$
$ REFERENCE DATA used:
$ - Design weight: 3.93857e+06 [N]
$ - Reference surface: 551 [m^2]
$ - Reference chord: 9.23877 [m]
$ - Reference span: 59.64 [m]
$ - Reference cruise altitude: 11000 [m]
$ - Max ceiling altitude: 13716 [m]
$ - User-defined reference surface for CLMAX, CLMAXLAND, CLALPHAD: 551 [m^2]
$
TRIM=   1
$ Sec. 25.303
$ Maximum load factor at VD, nz = 2.5, z=0m
$ VD: 178.032 m/s
$ Determine pitch control and angle of attack
TRIM    1       1       0.5232360.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     URDD5   0.0     URDD6   0.0     CLIMB   0.0     
        BANK    0.0     HEAD    0.0     URDD3   24.525  aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   2
$ Sec. 25.303
$ Maximum load factor at VD, nz = 2.5, z=8051m
$ VD: 272.754 m/s
$ Determine pitch control and angle of attack
TRIM    2       1       0.8860448051    SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     URDD5   0.0     URDD6   0.0     CLIMB   0.0     
        BANK    0.0     HEAD    0.0     URDD3   24.525  aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   3
$ Sec. 25.303
$ Maximum load factor at VC, nz = 2.5, z=0m
$ VC: 143.193 m/s
$ Determine pitch control and angle of attack
TRIM    3       1       0.4208450.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     URDD5   0.0     URDD6   0.0     CLIMB   0.0     
        BANK    0.0     HEAD    0.0     URDD3   24.525  aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   4
$ Sec. 25.303
$ Maximum load factor at VC, nz = 2.5, z=11000m
$ VC: 262.745 m/s
$ Determine pitch control and angle of attack
TRIM    4       1       0.89046 11000   SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     URDD5   0.0     URDD6   0.0     CLIMB   0.0     
        BANK    0.0     HEAD    0.0     URDD3   24.525  aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   5
$ Sec. 25.331 b1
$ Sudden aft movement of pitch control at VA=sqrt(nmax) * VS , z=0m
$  VA: 139.465 m/s
$  VS: 88.2053 m/s
$ Determine pitch control and angle of attack
$ Check control deflection is between -0 and 0
TRIM    5       1       0.4098290.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     BANK    0.0     URDD6   0.0     CLIMB   0.0     
        HEAD    0.0     URDD3   9.81    URDD5   0.359648aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   6
$ Sec. 23.331 b1
$ Sudden aft movement of pitch control at VC, z=0m
$  VC: 143.193 m/s
$ Determine pitch control and angle of attack
$ Check control deflection is between -0 and 0
TRIM    6       1       0.4208450.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     BANK    0.0     URDD6   0.0     CLIMB   0.0     
        HEAD    0.0     URDD3   9.81    URDD5   0.359648aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   7
$ Sec. 23.331 b1
$ Sudden aft movement of pitch control at VD, z=0m
$  VD: 178.032 m/s
$ Determine pitch control and angle of attack
$ Check control deflection is between -0 and 0
TRIM    7       1       0.5232360.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     BANK    0.0     URDD6   0.0     CLIMB   0.0     
        HEAD    0.0     URDD3   9.81    URDD5   0.359648aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   8
$ Sec. 25.331 b1
$ Sudden aft movement of pitch control at VA=sqrt(nmax) * VS , z=0m
$  VA: 139.465 m/s
$  VS: 88.2053 m/s
$ Determine pitch control and angle of attack
$ Check control deflection is between -0 and 0
TRIM    8       1       0.4098290.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     BANK    0.0     URDD6   0.0     CLIMB   0.0     
        HEAD    0.0     URDD3   24.525  URDD5   -0.23976aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   9
$ Sec. 23.331 b1
$ Sudden aft movement of pitch control at VC, z=0m
$  VC: 143.193 m/s
$ Determine pitch control and angle of attack
$ Check control deflection is between -0 and 0
TRIM    9       1       0.4208450.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     BANK    0.0     URDD6   0.0     CLIMB   0.0     
        HEAD    0.0     URDD3   24.525  URDD5   -0.23976aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   10
$ Sec. 23.331 b1
$ Sudden aft movement of pitch control at VD, z=0m
$  VD: 178.032 m/s
$ Determine pitch control and angle of attack
$ Check control deflection is between -0 and 0
TRIM    10      1       0.5232360.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     BANK    0.0     URDD6   0.0     CLIMB   0.0     
        HEAD    0.0     URDD3   24.525  URDD5   -0.23976aileronr0       
        flap1r  0       flap2r  0       rudder1 0       
TRIM=   11
$ Sec. 25.349 a
$ Sideslip maneuver at max rudder deflection at VA=sqrt(nmax) * VS, z=0m
$  VA: 139.465 m/s
$  VS: 88.2053 m/s
$ Determine pitch control, angle of attack, lateral acceleration, roll and yaw accelerations
TRIM    11      0       0.4098290.0     HEAD    0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     SIDES   0.0     THRUST  0.0     
        BANK    0.0     CLIMB   0.0     URDD5   0.0     URDD3   9.81    
        aileronr0       flap1r  0       flap2r  0       rudder1 0       
TRIM=   12
$ Sec. 25.351
$ Sideslip maneuver at overswing sideslip angle 22.5 deg at VA=sqrt(nmax) * VS, z=0m
$  VA: 139.465 m/s
$  VS: 88.2053 m/s
$ Determine pitch control, angle of attack, lateral acceleration, roll and yaw accelerations
TRIM    12      0       0.4098290.0     HEAD    0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     SIDES   22.5    THRUST  0.0     
        BANK    0.0     CLIMB   0.0     URDD5   0.0     URDD3   9.81    
        aileronr0       flap1r  0       flap2r  0       rudder1 0       
TRIM=   13
$ Sec. 25.351
$ Sideslip maneuver at sideslip angle 15 at VA=sqrt(nmax) * VS, z=0m
$  VA: 139.465 m/s
$  VS: 88.2053 m/s
$ Determine pitch control, angle of attack, lateral acceleration, roll and yaw accelerations
TRIM    13      0       0.4098290.0     HEAD    0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     SIDES   15      THRUST  0.0     
        BANK    0.0     CLIMB   0.0     URDD5   0.0     URDD3   9.81    
        aileronr0       flap1r  0       flap2r  0       rudder1 0       
TRIM=   14
$ Sec. 25.349 a
$ Sideslip maneuver at max rudder deflection at VS, z=0m
$  VS: 88.2053 m/s
$ Determine pitch control, angle of attack, lateral acceleration, roll and yaw accelerations
TRIM    14      0       0.2591990.0     HEAD    0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     SIDES   0.0     THRUST  0.0     
        BANK    0.0     CLIMB   0.0     URDD5   0.0     URDD3   9.81    
        aileronr0       flap1r  0       flap2r  0       rudder1 0       
TRIM=   15
$ Sec. 25.351
$ Sideslip maneuver at overswing sideslip angle 22.5 deg at VS, z=0m
$  VS: 88.2053 m/s
$ Determine pitch control, angle of attack, lateral acceleration, roll and yaw accelerations
TRIM    15      0       0.2591990.0     HEAD    0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     SIDES   22.5    THRUST  0.0     
        BANK    0.0     CLIMB   0.0     URDD5   0.0     URDD3   9.81    
        aileronr0       flap1r  0       flap2r  0       rudder1 0       
TRIM=   16
$ Sec. 25.351
$ Sideslip maneuver at sideslip angle 15 at VS, z=0m
$  VS: 88.2053 m/s
$ Determine pitch control, angle of attack, lateral acceleration, roll and yaw accelerations
TRIM    16      0       0.2591990.0     HEAD    0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     SIDES   15      THRUST  0.0     
        BANK    0.0     CLIMB   0.0     URDD5   0.0     URDD3   9.81    
        aileronr0       flap1r  0       flap2r  0       rudder1 0       
ITRIM= 1       
ITRIM= 2       
ITRIM= 3       
ITRIM= 4       
ITRIM= 5       
ITRIM= 3       
ITRIM= 1       
ITRIM= 5       
ITRIM= 3       
ITRIM= 1       
ITRIM= 5       
ITRIM= 5       
ITRIM= 5       
ITRIM= 6       
ITRIM= 6       
ITRIM= 6       